### ISSUE TITLE
Input file description

### ISSUE THREAD

**Issue by gcday** [Mia-yao/TCR-convergence#1]
Hello,

Very interesting concept--excited to compare TCR-convergence to immunotherapy response in some of our data!

For single-cell TCR data, could you please clarify what the contents of each field/column in the "tcr_di.csv" and "tcr.csv" files should be?

Also, could you please explain what the "TRA" and "TRB" columns in the "filtered_contig_annotations.csv" script are supposed to contain? The rest of the columns I can pull out from the standard "filtered_contig_annotations.csv" columns produced by current versions of 10X's cellranger pipeline--is that how I should generate this input file?

Could also be helpful to provide a few example input files (even with only a few entries each)  so we can see how we should format them.

Thanks!

Grady

**Comment by Mia-yao** [comment]
Hi Grady,

I am glad to know that you are interested in our research!

I've modified the script for finding convergent TCR using scTCR-seq data so that everyone can find convergent T cells in their data easily. Now the only input file needed would be the standard "filtered_contig_annotations.csv" file produced by current versions of 10X's cellranger pipeline.

Once you run the script, the convergent TCRs would be output in the 'Convergence.cvs' file. Feel free to leave a comment if you have further questions.

Thanks,
Mingyao

**Comment by Mia-yao** [comment]
issue closed
